<?php

/**
 * Localizations for add_calendar plugin
 */

$labels = array();
$labels['add_calendar'] = 'Add calendar';
$labels['calendarname'] = 'Calendar name';
$labels['addcalendar_in'] = 'Add calendar in';
$labels['usercalendars'] = 'Calendars';
$labels['calendarusername'] = 'Calendar user';
$labels['calendar'] = 'Calendar';
$labels['calendarurl'] = 'Calendar URL';
$labels['nofetch'] = 'No calendars available';
$labels['delete'] = 'Delete';

$messages = array();
$messages['successfullysaved'] = 'Saved successfully!';
$messages['created'] = 'Successfully created';
$messages['deleted'] = 'Successfully deleted';
$messages['unathorized'] = 'Not authorized';
$messages['exist'] = 'Already exist';
$messages['internalerror'] = 'Internal server error.';
$messages['calendarnameempty'] = 'Calendar name is empty';
$messages['urlempty'] = 'Calendar URL is empty';
$messages['tdidempty'] = 'Table row id is empty';
$messages['confirmcalendardelete'] = 'Are you sure you want to delete selected calendar';
?>
