<?php
$labels = array();
$labels['aliases'] = 'Aliases';
$labels['autoreply'] = "Send a notification";
$labels['autoreplystatus'] = "Enable vacation reply";
$labels['autoreplyextstatus'] = "Separate message for external users ";
$labels['autoreplybutton'] = 'Save';
$labels['autoreplymessage'] = 'Message Body';
$labels['autoreplymessage_externaluser'] = 'Autoreply message <br>for external user';
$labels['autoreplysubject'] = 'Subject';
$labels['autoreplysubject_externaluser'] = 'Subject for external users';
$labels['autoreplytimeinterval'] = 'Time interval in hours';
$labels['autoreplymaxnoofreply'] = 'Max number of replies';
$labels['autoreplystartdate'] = 'Start date (dd/mm/yyyy)';
$labels['autoreplyenddate'] = 'End date (dd/mm/yyyy)';
$labels['failed'] = 'Setting vacation reply failed!';
$labels['forward'] = 'Forwarding settings';
$labels['forwardingaddresses'] = 'Forward mail to';
$labels['keepcopy'] = 'Keep a copy of the mail';
$labels['mailforward'] = 'Mail Forwarding';
$labels['outofoffice'] = 'Vacation (Out of Office) Notification';
$labels['separate_alias'] = 'Separate each alias address by a comma';
$labels['separate_forward'] = 'Separate each forward address by a comma';
$labels['success_changed'] = 'Vacation settings succesfully changed';
$labels['vacation'] = 'Vacation Reply';
// Button text
$labels['aliasesbutton'] = 'Get aliases';
?>
