<?php

$labels = array();
$labels['server_side_filter']  = 'Filters';
$labels['filters'] = 'Filters';
$labels['storedfilters'] = 'Stored filters';
$labels['whatfilter'] = 'Filter';
$labels['searchstring'] = 'Contains';
$labels['movefrom'] = 'Check folder';
$labels['moveto'] = 'Move to';
$labels['from'] = 'From';
$labels['to'] = 'To';
$labels['cc'] = 'CC';
$labels['subject'] = 'Subject';
$labels['delete'] = 'Delete';
$labels['filterpriority'] = 'Do not apply other rules';

$messages = array();
$messages['nosearchstring'] = "The field 'Contains' cannot be empty.";
$messages['successfullysaved'] = "Filter successfully stored.";
$messages['unsuccessfullysaved'] = "Error: filter not stored.";
$messages['successfullydeleted'] = "Filter successfully deleted.";
$messages['unsuccessfullydeleted'] = "Error: filter not deleted.";
$messages['unsuccessfullload'] = "Error: failed to load filter, please refresh the page";
$messages['msg_if_field'] = 'If the field';
$messages['msg_contains'] = 'contains';
$messages['msg_move_msg_in'] = 'move the message to';
$messages['msg_move_msg_from'] = 'from';
$messages['msg_no_stored_filters'] = "There aren't filters stored.";
$messages['permissionerror'] = "Error: not having permission to save filter";

?>
