<?php

$labels = array();

# NEW
$labels['interface_options'] = 'Opcje Interfejsu';

# NEW
$labels['current_device'] = 'Typ obecnego urządzenia';

# NEW
$labels['desktop'] = 'Desktop';

# NEW
$labels['tablet'] = 'Tablet';

# NEW
$labels['phone'] = 'Telefon';

# NEW
$labels['desktop_skin'] = 'Skórka na desktopie';

# NEW
$labels['tablet_skin'] = 'Skórka na tablecie';

# NEW
$labels['phone_skin'] = 'Skórka na telefonie';

# NEW
$labels['select_desktop_skin'] = 'Wybierz skórkę na desktop';

# NEW
$labels['select_tablet_skin'] = 'Wybierz skórkę na tablet';

# NEW
$labels['select_phone_skin'] = 'Wybierz skórkę na telefon';

# NEW
$labels['disable_mobile_skin'] = 'Użyj skórki na desktop';

# NEW
$labels['enable_mobile_skin'] = 'Użyj skórki mobilnej';

