<?php
$labels = array();
$labels['customize_login'] = 'Customize login page';
$labels['preview_login'] = 'Preview login page';
$labels['success_changed'] = 'Changes succesfully applied';
$labels['failed'] = 'Changes were not applied!';
$labels['get_file_failed'] = 'File could not be fetched!';
$labels['file_uploaded_failed'] = 'File failed to upload!';
$labels['file_uploaded'] = 'File successfully uploaded';
$labels['file_size_exceeded'] = 'Total logo upload size exceeded. Maximum limit is 200KB';
$labels['reset_default_failed'] = 'Resetting background to default settings failed';
$labels['reset_default_success'] = 'Resetted background settings to default successfully';
$labels['reset_toggle_failed'] = 'There was an error toggling the background reset option';
?>
