<?php

$labels = [];

$labels['quota_plugin_title'] = 'Mailbox Quota';
$labels['chart_title'] = 'Space Chart';
$labels['space_used'] = 'Storage Used';
$labels['space_allocated'] = 'Allocated Quota';
$labels['space_percentage'] = 'Storage Percentage';
$labels['automail_deletion'] = 'Mail Lifetime';
$labels['space_free'] = 'Space free';
$labels['quota_meet_90'] = 'You have used over 90% of your storage quota.';
$labels['quota_meet_99'] = 'You have used over 99% of your storage quota.';
$labels['problem_please_contact'] = 'If you have any question, please contact %s.';
$labels['unknown'] = 'Unknown';
$labels['unlimited'] = 'Unlimited';
$labels['update_quota_label'] = 'Update Quota';
$labels['quota_update_success'] = 'Updated the used quota.';
$labels['quota_update_failed'] = 'Failed to update used quota. Please try again later.';
$labels['updatingquota'] = 'Updating Quota...';
$labels['not_applicable'] = 'NA';
$labels['not_available'] = 'Not Available';
