<?php

$labels = array();
$labels['ideolve'] = 'Ideolve';

$messages = array();
$messages['ideolvetitle'] = 'Ideolve';

$labels['clientid'] = 'Ideolve Client ID ';
$labels['clientsecret'] = 'Ideolve Api Key ';

$messages = array();
$messages['nodata'] = "The field cannot be empty.";

$messages['noclientid'] = "The field 'Ideolve Client ID' cannot be empty.";
$messages['noclientsecret'] = "The field 'Ideolve Api Key' cannot be empty.";

$messages['successfullysaved'] = "Successfully Updated.";
$messages['unsuccessfullysaved'] = "Failed to update.";
?>
