<?php

/**
 * Localizations for subscribe_calendar plugin
 */

$labels = array();
$labels['subscribe_calendar'] = 'Subscribe calendar';
$labels['subsribeinvites'] = 'Calendar subscribe invitations';
$labels['subsribedcalendars'] = 'Subscribed calendars';
$labels['calendar'] = 'Calendar';
$labels['calendarurl'] = 'Calendar URL';
$labels['invitedate'] = 'Invite date';
$labels['invitee'] = 'Invitee';
$labels['summary'] = 'Summary';
$labels['accept'] = 'Accept';
$labels['decline'] = 'Decline';
$labels['sharedby'] = 'Shared by';

$messages = array();
$messages['subscribed'] = 'Successfully subscribed';
$messages['declined'] = 'Successfully declined';
$messages['unathorized'] = 'Not authorized';
$messages['internalerror'] = 'Internal server error.';
$messages['calendarnameempty'] = 'Calendar name is empty';
$messages['responseempty'] = 'Invite response is empty';
$messages['hosturlempty'] = 'Host URL is empty';
$messages['uidempty'] = 'Invite UID is empty';
$messages['summaryempty'] = 'Invite summary is empty';
$messages['organizerempty'] = 'Organizer is empty';
$labels['noinvitefetch'] = 'No invitation available';
$labels['nosubscribedfetch'] = 'No subscribed calendar available';
?>
