<?php

/**
 * Localizations for share_calendar plugin
 */

$labels = array();
$labels['share_calendar'] = 'Share calendar';
$labels['calendarname'] = 'Calendar name';
$labels['sharecalendar_of'] = 'Share calendar of';
$labels['sharewith'] = 'Share with';
$labels['canwrite'] = 'Can write';
$labels['sharedcalendars'] = 'Shared calendars';
$labels['sharedwith'] = 'Shared with';
$labels['access'] = 'Access';
$labels['status'] = 'Status';
$labels['unshare'] = 'Unshare';
$labels['noshare'] = 'Not shared';
$labels['share'] = 'Share';

$messages = array();
$messages['successfullyshared'] = 'Successfully shared';
$messages['successfullyunshared'] = 'Successfully unshared';
$messages['unathorized'] = 'Not authorized';
$messages['exist'] = 'Already exist';
$messages['internalerror'] = 'Internal server error.';
$messages['calendarnameempty'] = 'Calendar name is empty';
$messages['tableidempty'] = 'Unshare table data is empty';
$messages['tdidempty'] = 'Unshare table data is empty';
$messages['urlempty'] = 'Calendar URL is empty';
$messages['calendardisplaynameempty'] = 'Calendar name is empty';
$messages['unsharewithempty'] = 'User is empty to unshare';

?>
