<?php

$labels = array();
$labels['zoom'] = 'Zoom';

$messages = array();
$messages['zoomtitle'] = 'Zoom';

$labels['clientid'] = 'Zoom Client ID ';
$labels['clientsecret'] = 'Zoom Client Secret ';

$messages = array();
$messages['nodata'] = "The field cannot be empty.";

$messages['noclientid'] = "The field 'Zoom Client ID' cannot be empty.";
$messages['noclientsecret'] = "The field 'Zoom Client Secret' cannot be empty.";

$messages['successfullysaved'] = "Successfully Updated.";
$messages['unsuccessfullysaved'] = "Failed to update.";
?>
